use config::Config;

/// Tests for Config struct and loading functionality
/// Generated by Agent B for comprehensive coverage of config module

#[test]
fn test_config_default() {
    let config = Config::default();
    assert!(config.upstream_url.is_empty());
    assert!(config.disabled_entities.is_empty());
}


#[test]
fn test_load_valid_config() {
    let temp_file = "/tmp/test_obscura_valid.toml";
    let toml_content = r#"

upstream_url = "http://localhost:8081"
disabled_entities = ["EMAIL", "PHONE"]
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.upstream_url, "http://localhost:8081");
    assert_eq!(config.disabled_entities, vec!["EMAIL", "PHONE"]);

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_minimal_config() {
    let temp_file = "/tmp/test_obscura_minimal.toml";
    let toml_content = "\n";
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert!(config.upstream_url.is_empty());
    assert!(config.disabled_entities.is_empty());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_empty_file() {
    let temp_file = "/tmp/test_obscura_empty.toml";
    std::fs::write(temp_file, "").unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert!(config.upstream_url.is_empty());
    assert!(config.disabled_entities.is_empty());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_partial_config_upstream_only() {
    let temp_file = "/tmp/test_obscura_partial_upstream.toml";
    let toml_content = r#"

upstream_url = "https://api.example.com"
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.upstream_url, "https://api.example.com");
    assert!(config.disabled_entities.is_empty());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_partial_config_disabled_entities_only() {
    let temp_file = "/tmp/test_obscura_partial_entities.toml";
    let toml_content = r#"

disabled_entities = ["SSN", "CREDIT_CARD", "DOB"]
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert!(config.upstream_url.is_empty());
    assert_eq!(config.disabled_entities, vec!["SSN", "CREDIT_CARD", "DOB"]);

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_empty_disabled_entities_array() {
    let temp_file = "/tmp/test_obscura_empty_array.toml";
    let toml_content = r#"

disabled_entities = []
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert!(config.disabled_entities.is_empty());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_missing_file() {
    let result = Config::load_from_file("/tmp/nonexistent_obscura_config.toml");
    assert!(result.is_err());
}

#[test]
fn test_load_invalid_toml_syntax() {
    let temp_file = "/tmp/test_obscura_invalid_syntax.toml";
    let toml_content = r#"
[app
upstream_url = "missing bracket"
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let result = Config::load_from_file(temp_file);
    assert!(result.is_err());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_invalid_toml_type_mismatch() {
    let temp_file = "/tmp/test_obscura_type_mismatch.toml";
    let toml_content = r#"

upstream_url = 12345
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let result = Config::load_from_file(temp_file);
    assert!(result.is_err());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_invalid_disabled_entities_not_array() {
    let temp_file = "/tmp/test_obscura_entities_not_array.toml";
    let toml_content = r#"

disabled_entities = "EMAIL,PHONE"
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let result = Config::load_from_file(temp_file);
    assert!(result.is_err());

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_config_with_extra_fields() {
    let temp_file = "/tmp/test_obscura_extra_fields.toml";
    let toml_content = r#"

upstream_url = "http://localhost:9000"
disabled_entities = ["NAME"]
extra_field = "ignored"
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.upstream_url, "http://localhost:9000");
    assert_eq!(config.disabled_entities, vec!["NAME"]);

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_config_with_single_disabled_entity() {
    let temp_file = "/tmp/test_obscura_single_entity.toml";
    let toml_content = r#"

disabled_entities = ["EMAIL"]
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.disabled_entities.len(), 1);
    assert_eq!(config.disabled_entities[0], "EMAIL");

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_config_with_many_disabled_entities() {
    let temp_file = "/tmp/test_obscura_many_entities.toml";
    let toml_content = r#"

disabled_entities = ["EMAIL", "PHONE", "SSN", "CREDIT_CARD", "DOB", "NAME", "ORG", "LOCATION", "IPV4"]
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.disabled_entities.len(), 9);
    assert!(config.disabled_entities.contains(&"EMAIL".to_string()));
    assert!(config.disabled_entities.contains(&"IPV4".to_string()));

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_config_boundary_empty_upstream_url() {
    let temp_file = "/tmp/test_obscura_empty_upstream.toml";
    let toml_content = r#"

upstream_url = ""
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.upstream_url, "");

    std::fs::remove_file(temp_file).unwrap();
}

#[test]
fn test_load_config_with_whitespace_in_entities() {
    let temp_file = "/tmp/test_obscura_whitespace_entities.toml";
    let toml_content = r#"

disabled_entities = ["EMAIL", " PHONE ", "SSN"]
"#;
    std::fs::write(temp_file, toml_content).unwrap();

    let config = Config::load_from_file(temp_file).unwrap();
    assert_eq!(config.disabled_entities.len(), 3);
    assert_eq!(config.disabled_entities[1], " PHONE ");

    std::fs::remove_file(temp_file).unwrap();
}
