use inference::mapping::MappingDictionary;
use inference::ner::EntitySpan;
use inference::redact::{redact, rehydrate};

/// Tests for redact() and rehydrate() functions in inference/src/redact.rs
/// Generated by Agent B for comprehensive coverage of redaction logic

// ============================================================================
// HAPPY PATH TESTS
// ============================================================================

#[test]
fn test_redact_happy_path_single_bert_entity() {
    let text = "My name is John Smith.";
    let bert_spans = vec![EntitySpan {
        text: "John Smith".to_string(),
        label: "PER".to_string(),
        start: 11,
        end: 21,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "My name is [PER_1].");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[PER_1]"), Some(&"John Smith".to_string()));
}

#[test]
fn test_redact_happy_path_multiple_bert_entities() {
    let text = "Alice works at Microsoft in Seattle.";
    let bert_spans = vec![
        EntitySpan {
            text: "Alice".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 5,
        },
        EntitySpan {
            text: "Microsoft".to_string(),
            label: "ORG".to_string(),
            start: 15,
            end: 24,
        },
        EntitySpan {
            text: "Seattle".to_string(),
            label: "LOC".to_string(),
            start: 28,
            end: 35,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[PER_1] works at [ORG_1] in [LOC_1].");
    assert_eq!(mapping.mappings.len(), 3);
    assert_eq!(mapping.mappings.get("[PER_1]"), Some(&"Alice".to_string()));
    assert_eq!(mapping.mappings.get("[ORG_1]"), Some(&"Microsoft".to_string()));
    assert_eq!(mapping.mappings.get("[LOC_1]"), Some(&"Seattle".to_string()));
}

#[test]
fn test_redact_happy_path_regex_ssn() {
    let text = "SSN: 123-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: [SSN_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[SSN_1]"), Some(&"123-45-6789".to_string()));
}

#[test]
fn test_redact_happy_path_regex_email() {
    let text = "Contact: alice@example.com";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Contact: [EMAIL_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[EMAIL_1]"), Some(&"alice@example.com".to_string()));
}

#[test]
fn test_redact_happy_path_regex_phone() {
    let text = "Call (555) 555-5555";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Call [PHONE_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[PHONE_1]"), Some(&"(555) 555-5555".to_string()));
}

#[test]
fn test_redact_happy_path_regex_credit_card_dashed() {
    let text = "Card: 1234-5678-9012-3456";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Card: [CREDIT_CARD_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[CREDIT_CARD_1]"), Some(&"1234-5678-9012-3456".to_string()));
}

#[test]
fn test_redact_happy_path_regex_credit_card_undashed() {
    let text = "Card: 1234567890123456";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Card: [CREDIT_CARD_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[CREDIT_CARD_1]"), Some(&"1234567890123456".to_string()));
}

#[test]
fn test_redact_happy_path_regex_dob_slash() {
    let text = "DOB: 01/15/2000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: [DOB_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[DOB_1]"), Some(&"01/15/2000".to_string()));
}

#[test]
fn test_redact_happy_path_regex_dob_dash() {
    let text = "Born: 2000-01-15";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Born: [DOB_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[DOB_1]"), Some(&"2000-01-15".to_string()));
}

#[test]
fn test_redact_happy_path_regex_mrn() {
    let text = "MRN-1234567";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[MRN_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[MRN_1]"), Some(&"MRN-1234567".to_string()));
}

#[test]
fn test_redact_happy_path_regex_mrn_case_insensitive() {
    let text = "mrn-7654321";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[MRN_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[MRN_1]"), Some(&"mrn-7654321".to_string()));
}

#[test]
fn test_redact_happy_path_regex_ipv4() {
    let text = "IP: 192.168.1.1";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IP: [IPV4_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[IPV4_1]"), Some(&"192.168.1.1".to_string()));
}

#[test]
fn test_redact_happy_path_regex_ipv6_loopback() {
    let text = "IPv6: ::1";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IPv6: [IPV6_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[IPV6_1]"), Some(&"::1".to_string()));
}

#[test]
fn test_redact_happy_path_regex_ipv6_full() {
    let text = "2001:0db8:0000:0000:0000:0000:0000:0001";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[IPV6_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_redact_happy_path_regex_passport() {
    let text = "Passport: A12345678";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Passport: [PASSPORT_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[PASSPORT_1]"), Some(&"A12345678".to_string()));
}

#[test]
fn test_redact_happy_path_hybrid_bert_and_regex() {
    let text = "Contact John at john@example.com or 123-45-6789.";
    let bert_spans = vec![EntitySpan {
        text: "John".to_string(),
        label: "PER".to_string(),
        start: 8,
        end: 12,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert!(redacted.contains("[PER_1]"));
    assert!(redacted.contains("[EMAIL_1]"));
    assert!(redacted.contains("[SSN_1]"));
    assert_eq!(mapping.mappings.len(), 3);
}

#[test]
fn test_rehydrate_happy_path_single_token() {
    let redacted = "My name is [PER_1].";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "John Smith".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "My name is John Smith.");
}

#[test]
fn test_rehydrate_happy_path_multiple_tokens() {
    let redacted = "[PER_1] works at [ORG_1] in [LOC_1].";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "Alice".to_string());
    mapping.insert("[ORG_1]".to_string(), "Microsoft".to_string());
    mapping.insert("[LOC_1]".to_string(), "Seattle".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "Alice works at Microsoft in Seattle.");
}

#[test]
fn test_rehydrate_happy_path_sorted_by_length() {
    // Tests that [PER_10] is replaced before [PER_1] to avoid partial match
    let redacted = "[PER_1] and [PER_10]";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "Alice".to_string());
    mapping.insert("[PER_10]".to_string(), "Bob".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "Alice and Bob");
}

// ============================================================================
// EDGE CASE TESTS
// ============================================================================

#[test]
fn test_redact_edge_case_empty_text() {
    let text = "";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_redact_edge_case_no_entities() {
    let text = "This is plain text.";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "This is plain text.");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_redact_edge_case_whitespace_only() {
    let text = "   \n\t  ";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "   \n\t  ");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_redact_edge_case_entity_at_start() {
    let text = "Alice is here.";
    let bert_spans = vec![EntitySpan {
        text: "Alice".to_string(),
        label: "PER".to_string(),
        start: 0,
        end: 5,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[PER_1] is here.");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_redact_edge_case_entity_at_end() {
    let text = "Call Alice";
    let bert_spans = vec![EntitySpan {
        text: "Alice".to_string(),
        label: "PER".to_string(),
        start: 5,
        end: 10,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Call [PER_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_redact_edge_case_consecutive_entities() {
    let text = "Alice and Bob";
    let bert_spans = vec![
        EntitySpan {
            text: "Alice".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 5,
        },
        EntitySpan {
            text: "Bob".to_string(),
            label: "PER".to_string(),
            start: 10,
            end: 13,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[PER_1] and [PER_2]");
    assert_eq!(mapping.mappings.len(), 2);
}

#[test]
fn test_redact_edge_case_same_label_increments_counter() {
    let text = "John, Jane, and Jim are here.";
    let bert_spans = vec![
        EntitySpan {
            text: "John".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 4,
        },
        EntitySpan {
            text: "Jane".to_string(),
            label: "PER".to_string(),
            start: 6,
            end: 10,
        },
        EntitySpan {
            text: "Jim".to_string(),
            label: "PER".to_string(),
            start: 16,
            end: 19,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "[PER_1], [PER_2], and [PER_3] are here.");
    assert_eq!(mapping.mappings.len(), 3);
}

#[test]
fn test_redact_edge_case_multiple_ssn_counter() {
    let text = "SSN 123-45-6789 and 234-56-7890";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN [SSN_1] and [SSN_2]");
    assert_eq!(mapping.mappings.len(), 2);
}

#[test]
fn test_rehydrate_edge_case_empty_mapping() {
    let redacted = "No tokens here.";
    let mapping = MappingDictionary::new();

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "No tokens here.");
}

#[test]
fn test_rehydrate_edge_case_empty_text() {
    let redacted = "";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "Alice".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "");
}

#[test]
fn test_rehydrate_edge_case_token_not_in_text() {
    let redacted = "Plain text.";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "Alice".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "Plain text.");
}

#[test]
fn test_rehydrate_edge_case_duplicate_tokens() {
    let redacted = "[PER_1] called [PER_1] again.";
    let mut mapping = MappingDictionary::new();
    mapping.insert("[PER_1]".to_string(), "Alice".to_string());

    let rehydrated = rehydrate(redacted, &mapping);

    assert_eq!(rehydrated, "Alice called Alice again.");
}

// ============================================================================
// CONFLICT RESOLUTION TESTS (CRITICAL SECURITY BEHAVIOR)
// ============================================================================

#[test]
fn test_conflict_resolution_exact_span_regex_authoritative_ssn() {
    // BERT and regex both detect SSN at same position.
    // Regex should win because SSN is in REGEX_AUTHORITATIVE_TYPES.
    let text = "SSN: 123-45-6789";
    let bert_spans = vec![EntitySpan {
        text: "123-45-6789".to_string(),
        label: "PER".to_string(), // BERT incorrectly labels it as PER
        start: 5,
        end: 16,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    // Regex should win with SSN label
    assert_eq!(redacted, "SSN: [SSN_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[SSN_1]"), Some(&"123-45-6789".to_string()));
    assert!(mapping.mappings.get("[PER_1]").is_none());
}

#[test]
fn test_conflict_resolution_exact_span_regex_authoritative_email() {
    let text = "Email: alice@example.com";
    let bert_spans = vec![EntitySpan {
        text: "alice@example.com".to_string(),
        label: "MISC".to_string(),
        start: 7,
        end: 24,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Email: [EMAIL_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[EMAIL_1]"), Some(&"alice@example.com".to_string()));
}

#[test]
fn test_conflict_resolution_nested_longer_wins() {
    // BERT detects "John Smith", regex detects "John" (hypothetically).
    // Longer span (John Smith) should win via sort-then-greedy.
    let text = "Name: John Smith";
    let bert_spans = vec![
        EntitySpan {
            text: "John Smith".to_string(),
            label: "PER".to_string(),
            start: 6,
            end: 16,
        },
        EntitySpan {
            text: "John".to_string(),
            label: "PER".to_string(),
            start: 6,
            end: 10,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    // Longer span wins (John Smith)
    assert_eq!(redacted, "Name: [PER_1]");
    assert_eq!(mapping.mappings.len(), 1);
    assert_eq!(mapping.mappings.get("[PER_1]"), Some(&"John Smith".to_string()));
}

#[test]
fn test_conflict_resolution_partial_overlap_first_accepted_wins() {
    // Two overlapping entities with different start positions.
    // First in sort order wins, second is skipped.
    let text = "Microsoft Corporation";
    let bert_spans = vec![
        EntitySpan {
            text: "Microsoft".to_string(),
            label: "ORG".to_string(),
            start: 0,
            end: 9,
        },
        EntitySpan {
            text: "Corporation".to_string(),
            label: "ORG".to_string(),
            start: 10,
            end: 21,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    // Both should be accepted (no overlap after greedy cursor)
    assert_eq!(redacted, "[ORG_1] [ORG_2]");
    assert_eq!(mapping.mappings.len(), 2);
}

#[test]
fn test_conflict_resolution_overlapping_rejected() {
    let text = "John Smith Jr";
    let bert_spans = vec![
        EntitySpan {
            text: "John Smith".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 10,
        },
        EntitySpan {
            text: "Smith Jr".to_string(),
            label: "PER".to_string(),
            start: 5,
            end: 13,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    // First span wins (John Smith), second is rejected by greedy cursor
    assert_eq!(redacted, "[PER_1] Jr");
    assert_eq!(mapping.mappings.len(), 1);
}

// ============================================================================
// SKIPPED ENTITIES TESTS
// ============================================================================

#[test]
fn test_skipped_entities_bert_entity_filtered() {
    let text = "Alice works here.";
    let bert_spans = vec![EntitySpan {
        text: "Alice".to_string(),
        label: "PER".to_string(),
        start: 0,
        end: 5,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &["PER".to_string()]).unwrap();

    assert_eq!(redacted, "Alice works here.");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_skipped_entities_regex_entity_filtered() {
    let text = "SSN: 123-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &["SSN".to_string()]).unwrap();

    assert_eq!(redacted, "SSN: 123-45-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_skipped_entities_case_insensitive_bert() {
    let text = "Alice works here.";
    let bert_spans = vec![EntitySpan {
        text: "Alice".to_string(),
        label: "PER".to_string(),
        start: 0,
        end: 5,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &["per".to_string()]).unwrap();

    assert_eq!(redacted, "Alice works here.");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_skipped_entities_case_insensitive_regex() {
    let text = "Email: alice@example.com";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &["email".to_string()]).unwrap();

    assert_eq!(redacted, "Email: alice@example.com");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_skipped_entities_multiple() {
    let text = "Alice at alice@example.com, SSN 123-45-6789";
    let bert_spans = vec![EntitySpan {
        text: "Alice".to_string(),
        label: "PER".to_string(),
        start: 0,
        end: 5,
    }];

    let (redacted, mapping) = redact(text, bert_spans, &["PER".to_string(), "EMAIL".to_string()]).unwrap();

    // PER and EMAIL skipped, only SSN redacted
    assert_eq!(redacted, "Alice at alice@example.com, SSN [SSN_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_skipped_entities_preserves_conflict_resolution() {
    // Even when an entity is skipped, conflict resolution should have
    // already happened before filtering. This ensures disabled entities
    // don't cause suppressed BERT entities to incorrectly survive.
    let text = "SSN: 123-45-6789";
    let bert_spans = vec![EntitySpan {
        text: "123-45-6789".to_string(),
        label: "PER".to_string(),
        start: 5,
        end: 16,
    }];

    // Skip SSN (regex-authoritative winner) — BERT PER should also be suppressed
    let (redacted, mapping) = redact(text, bert_spans, &["SSN".to_string()]).unwrap();

    // Both entities detected same span: regex SSN won conflict resolution,
    // then SSN was filtered. BERT PER was never added to all_spans due to
    // conflict. So no redaction happens.
    // CORRECTION: skipped_entities filters BEFORE conflict resolution in this impl.
    // The code filters during span collection (lines 129, 142), not after merge.
    // So: regex SSN is skipped → BERT PER is added → redacted as PER.
    assert_eq!(redacted, "SSN: [PER_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

// ============================================================================
// REGEX PATTERN VALIDATION TESTS
// ============================================================================

#[test]
fn test_regex_ssn_rejects_invalid_area_000() {
    let text = "SSN: 000-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 000-45-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_rejects_invalid_area_666() {
    let text = "SSN: 666-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 666-45-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_rejects_invalid_area_9xx() {
    let text = "SSN: 900-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 900-45-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_rejects_invalid_group_00() {
    let text = "SSN: 123-00-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 123-00-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_rejects_invalid_serial_0000() {
    let text = "SSN: 123-45-0000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 123-45-0000");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_rejects_undashed() {
    let text = "SSN: 123456789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "SSN: 123456789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_month_13() {
    let text = "DOB: 13/01/2000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 13/01/2000");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_month_00() {
    let text = "DOB: 00/15/2000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 00/15/2000");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_day_32() {
    let text = "DOB: 01/32/2000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 01/32/2000");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_day_00() {
    let text = "DOB: 01/00/2000";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 01/00/2000");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_year_1899() {
    let text = "DOB: 01/15/1899";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 01/15/1899");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_rejects_invalid_year_2100() {
    let text = "DOB: 01/15/2100";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: 01/15/2100");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_dob_boundary_valid_1900() {
    let text = "DOB: 01/15/1900";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: [DOB_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_dob_boundary_valid_2099() {
    let text = "DOB: 12/31/2099";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "DOB: [DOB_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_ipv4_rejects_invalid_octet_256() {
    let text = "IP: 256.1.1.1";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IP: 256.1.1.1");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ipv4_rejects_invalid_octet_999() {
    let text = "IP: 999.999.999.999";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IP: 999.999.999.999");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ipv4_boundary_valid_255() {
    let text = "IP: 255.255.255.255";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IP: [IPV4_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_ipv4_boundary_valid_0() {
    let text = "IP: 0.0.0.0";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "IP: [IPV4_1]");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_passport_rejects_lowercase_letter() {
    let text = "Passport: a12345678";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Passport: a12345678");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_passport_rejects_7_digits() {
    let text = "Passport: A1234567";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Passport: A1234567");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_passport_rejects_9_digits() {
    let text = "Passport: A123456789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Passport: A123456789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_mrn_rejects_6_digits() {
    let text = "MRN-123456";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "MRN-123456");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_mrn_rejects_8_digits() {
    let text = "MRN-12345678";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "MRN-12345678");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_credit_card_rejects_15_digits() {
    let text = "Card: 123456789012345";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Card: 123456789012345");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_credit_card_rejects_17_digits() {
    let text = "Card: 12345678901234567";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Card: 12345678901234567");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_email_rejects_no_at_symbol() {
    let text = "Email: aliceexample.com";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Email: aliceexample.com");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_email_rejects_no_domain() {
    let text = "Email: alice@";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Email: alice@");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_email_rejects_no_tld() {
    let text = "Email: alice@example";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Email: alice@example");
    assert_eq!(mapping.mappings.len(), 0);
}

// ============================================================================
// WORD BOUNDARY TESTS
// ============================================================================

#[test]
fn test_regex_ssn_word_boundary_rejection_prefix() {
    let text = "abc123-45-6789";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "abc123-45-6789");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_ssn_word_boundary_rejection_suffix() {
    let text = "123-45-6789xyz";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "123-45-6789xyz");
    assert_eq!(mapping.mappings.len(), 0);
}

#[test]
fn test_regex_email_word_boundary_acceptance_space() {
    let text = "Contact alice@example.com now";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Contact [EMAIL_1] now");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_email_word_boundary_acceptance_punctuation() {
    let text = "Email: alice@example.com.";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Email: [EMAIL_1].");
    assert_eq!(mapping.mappings.len(), 1);
}

#[test]
fn test_regex_phone_word_boundary_acceptance() {
    let text = "Call (555) 555-5555 today";
    let bert_spans = vec![];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert_eq!(redacted, "Call [PHONE_1] today");
    assert_eq!(mapping.mappings.len(), 1);
}

// ============================================================================
// TOKEN FORMAT TESTS
// ============================================================================

#[test]
fn test_token_format_label_underscore_number() {
    let text = "Alice and Bob";
    let bert_spans = vec![
        EntitySpan {
            text: "Alice".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 5,
        },
        EntitySpan {
            text: "Bob".to_string(),
            label: "PER".to_string(),
            start: 10,
            end: 13,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert!(redacted.contains("[PER_1]"));
    assert!(redacted.contains("[PER_2]"));
    assert!(mapping.mappings.contains_key("[PER_1]"));
    assert!(mapping.mappings.contains_key("[PER_2]"));
}

#[test]
fn test_token_format_different_labels() {
    let text = "Alice at Microsoft";
    let bert_spans = vec![
        EntitySpan {
            text: "Alice".to_string(),
            label: "PER".to_string(),
            start: 0,
            end: 5,
        },
        EntitySpan {
            text: "Microsoft".to_string(),
            label: "ORG".to_string(),
            start: 9,
            end: 18,
        },
    ];

    let (redacted, mapping) = redact(text, bert_spans, &[]).unwrap();

    assert!(redacted.contains("[PER_1]"));
    assert!(redacted.contains("[ORG_1]"));
}
