use hyper::{HeaderMap, header};

/// Unit tests for proxy request handler logic components
/// Tests header parsing, URL construction, and entity merging behavior
/// Generated by Agent B for comprehensive coverage

#[test]
fn test_skip_redaction_header_single_entity() {
    let header_value = "EMAIL";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 1);
    assert_eq!(entities[0], "EMAIL");
}

#[test]
fn test_skip_redaction_header_multiple_entities() {
    let header_value = "EMAIL,PHONE,SSN";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 3);
    assert_eq!(entities, vec!["EMAIL", "PHONE", "SSN"]);
}

#[test]
fn test_skip_redaction_header_with_whitespace() {
    let header_value = "EMAIL, PHONE , SSN";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 3);
    assert_eq!(entities, vec!["EMAIL", "PHONE", "SSN"]);
}

#[test]
fn test_skip_redaction_header_empty_string() {
    let header_value = "";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    // Empty string splits to one empty element
    assert_eq!(entities.len(), 1);
    assert_eq!(entities[0], "");
}

#[test]
fn test_skip_redaction_header_single_comma() {
    let header_value = ",";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 2);
    assert_eq!(entities[0], "");
    assert_eq!(entities[1], "");
}

#[test]
fn test_skip_redaction_header_trailing_comma() {
    let header_value = "EMAIL,PHONE,";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 3);
    assert_eq!(entities[0], "EMAIL");
    assert_eq!(entities[1], "PHONE");
    assert_eq!(entities[2], "");
}

#[test]
fn test_skip_redaction_header_all_nine_entity_types() {
    let header_value = "EMAIL,PHONE,SSN,CREDIT_CARD,DOB,NAME,ORG,LOCATION,IPV4";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 9);
    assert!(entities.contains(&"EMAIL".to_string()));
    assert!(entities.contains(&"IPV4".to_string()));
}

#[test]
fn test_upstream_url_construction_with_path() {
    let upstream_url = "http://localhost:8081";
    let path_and_query = "/api/v1/users";
    let uri_string = format!("{}{}", upstream_url, path_and_query);

    assert_eq!(uri_string, "http://localhost:8081/api/v1/users");
}

#[test]
fn test_upstream_url_construction_with_query_params() {
    let upstream_url = "http://localhost:8081";
    let path_and_query = "/api/v1/users?id=123&name=test";
    let uri_string = format!("{}{}", upstream_url, path_and_query);

    assert_eq!(uri_string, "http://localhost:8081/api/v1/users?id=123&name=test");
}

#[test]
fn test_upstream_url_construction_root_path() {
    let upstream_url = "http://localhost:8081";
    let path_and_query = "/";
    let uri_string = format!("{}{}", upstream_url, path_and_query);

    assert_eq!(uri_string, "http://localhost:8081/");
}

#[test]
fn test_upstream_url_construction_empty_path_default() {
    let upstream_url = "http://localhost:8081";
    let path_and_query = "/"; // Fallback default from code
    let uri_string = format!("{}{}", upstream_url, path_and_query);

    assert_eq!(uri_string, "http://localhost:8081/");
}

#[test]
fn test_header_forwarding_excludes_host() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, "example.com".parse().unwrap());
    headers.insert(header::USER_AGENT, "test-agent".parse().unwrap());
    headers.insert(header::CONTENT_TYPE, "application/json".parse().unwrap());

    let forwarded: Vec<_> = headers.iter()
        .filter(|(key, _)| *key != header::HOST)
        .collect();

    assert_eq!(forwarded.len(), 2);
    assert!(forwarded.iter().any(|(k, _)| *k == header::USER_AGENT));
    assert!(forwarded.iter().any(|(k, _)| *k == header::CONTENT_TYPE));
    assert!(!forwarded.iter().any(|(k, _)| *k == header::HOST));
}

#[test]
fn test_header_forwarding_preserves_custom_headers() {
    let mut headers = HeaderMap::new();
    headers.insert("X-Custom-Header", "custom-value".parse().unwrap());
    headers.insert("X-Request-ID", "req-123".parse().unwrap());

    let forwarded: Vec<_> = headers.iter()
        .filter(|(key, _)| *key != header::HOST)
        .collect();

    assert_eq!(forwarded.len(), 2);
}

#[test]
fn test_disabled_entities_merge_config_and_header() {
    let config_entities = vec!["EMAIL".to_string(), "PHONE".to_string()];
    let header_value = "SSN,CREDIT_CARD";
    let header_overrides: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    let mut skipped_entities = config_entities.clone();
    skipped_entities.extend(header_overrides);

    assert_eq!(skipped_entities.len(), 4);
    assert!(skipped_entities.contains(&"EMAIL".to_string()));
    assert!(skipped_entities.contains(&"PHONE".to_string()));
    assert!(skipped_entities.contains(&"SSN".to_string()));
    assert!(skipped_entities.contains(&"CREDIT_CARD".to_string()));
}

#[test]
fn test_disabled_entities_merge_duplicates() {
    let config_entities = vec!["EMAIL".to_string(), "PHONE".to_string()];
    let header_value = "EMAIL,SSN";
    let header_overrides: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    let mut skipped_entities = config_entities.clone();
    skipped_entities.extend(header_overrides);

    assert_eq!(skipped_entities.len(), 4);
    // Duplicates are allowed in Vec, deduplication would require HashSet
    let email_count = skipped_entities.iter().filter(|e| *e == "EMAIL").count();
    assert_eq!(email_count, 2);
}

#[test]
fn test_disabled_entities_empty_config_with_header() {
    let config_entities: Vec<String> = vec![];
    let header_value = "SSN,DOB";
    let header_overrides: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    let mut skipped_entities = config_entities.clone();
    skipped_entities.extend(header_overrides);

    assert_eq!(skipped_entities.len(), 2);
    assert_eq!(skipped_entities, vec!["SSN", "DOB"]);
}

#[test]
fn test_disabled_entities_config_only_no_header() {
    let config_entities = vec!["EMAIL".to_string(), "PHONE".to_string()];
    let skipped_entities = config_entities.clone();

    assert_eq!(skipped_entities.len(), 2);
    assert_eq!(skipped_entities, vec!["EMAIL", "PHONE"]);
}

#[test]
fn test_uri_parsing_valid_format() {
    let uri_string = "http://localhost:8081/api/test";
    let result = uri_string.parse::<hyper::Uri>();
    assert!(result.is_ok());

    let uri = result.unwrap();
    assert_eq!(uri.path(), "/api/test");
}

#[test]
fn test_uri_parsing_with_query() {
    let uri_string = "http://localhost:8081/api?param=value";
    let result = uri_string.parse::<hyper::Uri>();
    assert!(result.is_ok());

    let uri = result.unwrap();
    assert_eq!(uri.path(), "/api");
    assert_eq!(uri.query(), Some("param=value"));
}

#[test]
fn test_disabled_entities_filter_empty_strings() {
    let header_value = "EMAIL,,PHONE";
    let entities: Vec<String> = header_value.split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();

    assert_eq!(entities.len(), 2);
    assert_eq!(entities, vec!["EMAIL", "PHONE"]);
}

#[test]
fn test_disabled_entities_case_sensitive() {
    let header_value = "email,EMAIL,Email";
    let entities: Vec<String> = header_value.split(',').map(|s| s.trim().to_string()).collect();

    assert_eq!(entities.len(), 3);
    assert!(entities.contains(&"email".to_string()));
    assert!(entities.contains(&"EMAIL".to_string()));
    assert!(entities.contains(&"Email".to_string()));
}
